#!/usr/bin/env python3

from urllib.request import urlopen
from bs4 import BeautifulSoup
from operator import itemgetter

html = urlopen('https://packages.altlinux.org/ru/sisyphus/maintainers')
bsObj = BeautifulSoup(html, 'lxml')

names = bsObj.find_all('a', style='color:var(--pf-global--Color--100)')
packages = bsObj.find_all('div', class_='pf-l-flex__item')

mergedList = [(names[i].text, int(packages[i].text)) for i in range(0, len(names))]

sortedList = sorted(mergedList, key=itemgetter(1), reverse=True)

for i in range(0, len(names)):
    print(f"{sortedList[i][1]:<4} {sortedList[i][0]}")
